create table Language (
	uid int GENERATED BY DEFAULT AS IDENTITY(start with 1) primary key,
	name varchar (50)
);

create table Author (
	uid int GENERATED BY DEFAULT AS IDENTITY(start with 1) primary key,
	firstName varchar (250),
	lastName varchar (250)
);

create table Publisher (
	uid int GENERATED BY DEFAULT AS IDENTITY(start with 1) primary key,
	name varchar (250),
	address varchar (250)
);

create table Book (
	uid int GENERATED BY DEFAULT AS IDENTITY(start with 1) primary key,
	name varchar (250),
	publisher_id int not null,
	author_id int not null,
	language_id int not null,
	date timestamp default current_timestamp,
	desc varchar (500)
);

insert into Language (name) values ('English');
insert into Language (name) values ('French');
insert into Language (name) values ('German');

insert into Author (firstName, lastName) values ('Craig', 'Walls');
insert into Author (firstName, lastName) values ('Gerbert', 'Wales');
insert into Author (firstName, lastName) values ('John', 'Smith');

insert into Publisher (name, address) values ('O''Reily', 'USA, New-York');
insert into Publisher (name, address) values ('BBC', 'UK, London');
insert into Publisher (name, address) values ('NoName', 'Nowhere');

insert into Book (name, publisher_id, author_id, language_id, desc) values ('Book 1', 1, 1, 1, 'Book 1 desc');
insert into Book (name, publisher_id, author_id, language_id, desc) values ('Book 2', 1, 1, 1, 'Book 2 desc');
insert into Book (name, publisher_id, author_id, language_id, desc) values ('Book 3', 1, 1, 1, 'Book 3 desc');
